In [6]:
import numpy as np
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Methods for Solving Linear Equations.

- We want to solve numerically a system of $n$ linear equations with $n$ unknowns of the form:

    \begin{align}
    a_{11}\,x_1+a_{12}\,x_2+\cdots+a_{1n}\,x_n &= b_1,\nonumber\\
    a_{21}\,x_1+a_{22}\,x_2+\cdots+a_{2n}\,x_n &= b_2,\nonumber\\
    \vdots\quad\qquad\vdots\qquad\qquad\vdots\quad&\quad\vdots\nonumber\\
    a_{n1}\,x_1+a_{n2}\,x_2+\cdots+a_{nn}\,x_n &=b_n,\nonumber\\
    \end{align}

    or in matrix formulation:

    $$A\cdot X =B,$$

    with

$$A=\left(
\begin{array}{cccc}
a_{11}&a_{12}&\cdots&a_{1n}\nonumber\\
a_{21}&a_{22}&\cdots&a_{2n}\nonumber\\
\vdots&\vdots&\ddots&\vdots\nonumber\\
a_{n1}&a_{n2}&\cdots&a_{nn}\nonumber\\
\end{array}\right),\quad
X=\left(
\begin{array}{c}
x_1\nonumber\\
x_2\nonumber\\
\vdots\nonumber\\
x_n\nonumber\\
\end{array}
\right)\quad\text{and}\quad B=\left(
\begin{array}{c}
b_1\nonumber\\
b_2\nonumber\\
\vdots\nonumber\\
b_n\nonumber\\
\end{array}
\right).
$$
<br/>

---

## Gaussian Elimination.

- The idea of the method is to use elementary matrix operations that allow us to transform our initial system of equations into one in which the matrix $A$ is triangular.

- To do this, we first construct the augmented matrix:

$$\left(A\vert B\right)=\left(
\begin{array}{cccccc}
a_{11}&a_{12}&\cdots&a_{1n}&\vert& b_1\nonumber\\
a_{21}&a_{22}&\cdots&a_{2n}&\vert& b_2\nonumber\\
\vdots&\vdots&\ddots&\vdots&\vert &\vdots\nonumber\\
a_{n1}&a_{n2}&\cdots&a_{nn}&\vert& b_n\nonumber\\
\end{array}\right)$$

- Elementary operations on the augmented matrix:

    1. Multiply a row by a (non-zero) scalar.
    2. Add to one row a multiple of another.
    3. Interchange the positions of two rows.
    
    
- The Gaussian method combines operations 1 and 2 to transform:

    $$\left(A\vert B\right)=\left(
    \begin{array}{ccccccc}
    a_{11}&a_{12}&a_{31}&\cdots&a_{1n}&\vert& b_1\nonumber\\
    a_{21}&a_{22}&a_{32}&\cdots&a_{2n}&\vert& b_2\nonumber\\
    a_{31}&a_{32}&a_{33}&\cdots&a_{3n}&\vert& b_3\nonumber\\
    \vdots&\vdots&\vdots&\ddots&\vdots&\vert &\vdots\nonumber\\
    a_{n1}&a_{n2}&a_{n3}&\cdots&a_{nn}&\vert& b_n\nonumber\\
    \end{array}\right)\quad\Rightarrow\quad 
    \left(
    \begin{array}{ccccccc}
     1 &\bar a_{12}&\bar a_{31}&\cdots&\bar a_{1n}&\vert&\bar b_1\nonumber\\
    0& 1&\bar a_{32}&\cdots&\bar a_{2n}&\vert&\bar b_2\nonumber\\
    0&0& 1 &\cdots&\bar a_{3n}&\vert&\bar b_3\nonumber\\
    \vdots&\vdots&\vdots&\ddots&\vdots&\vert &\vdots\nonumber\\
    0&0&0&\cdots& 1 &\vert&\bar b_n\nonumber\\
    \end{array}\right)$$

    where the second system of equations can be solved by back substitution.

**How can we obtain the triangular matrix?** 

- We divide the **first** row by the **first** element $a_{11}$.
- We subtract from row $j>1$ the first row multiplied by its first element $a_{j1}$.
- We divide the **second** row by its **second** element $a_{22}$.
- We subtract from row $j>2$ the second row multiplied by its first element $a_{j2}$.
- We continue in the same way until reaching the last element.

**How is back substitution performed?** 
- The value of $x_n=\bar b_n$.
- The value of $x_{n-1}=\bar b_{n-1} -\bar a_{n-1,n} x_n$.
- We continue subtracting from the previous rows the value of all the unknowns we have just solved, multiplied by their corresponding coefficient in the row.

---


In [7]:
def eligauss(A,B):
    """Gaussian Elimination for AX = B.

    Args:
        A (np.array): Main Matrix of the system
        B (np.array): Independent Matrix of the system

    Returns:
        np.array: X (value of n variables in the system of equations)
    """

    M = np.column_stack((A, B))
    N = len(B)
    
    for i in range(N):
        M[i, :] /= M[i, i]
        for j in range(i+1, N):
            M[j] -= M[j, i]*M[i, :]
            
    x = np.zeros([N, 1], float)
    for k in range(N-1, -1, -1):
        x[k] = M[k, N]
        for s in range(k+1, N):
            x[k] -= M[k, s]*x[s]
    return np.array(x)

A = np.array([[2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]], float)
B = np.array([[-4], [3], [9], [7]], float)
eligauss(A, B)

array([[ 2.],
       [-1.],
       [-2.],
       [ 1.]])

## Pivot Method.

- Gaussian elimination requires dividing at each step by the element $a_{ii}$, which is only possible if this element is nonzero.

- The pivot method combines Gaussian elimination with elementary matrix operation 3:  
  the interchange of one row with another.

- This guarantees that at no step will a diagonal element be equal to 0.

- There is no unique way to do this.

- The general rule is to interchange, at each step, row $m$ with a row $j>m$ such that $\vert a_{jm}\vert$ has the maximum value among all $a_{km}$ with $m\le k\le n$.

---


In [8]:
def eligausspiv(A,B):
    """Pivoting Gaussian Elimination for AX = B.

    Args:
        A (np.array): Main Matrix of the system
        B (np.array): Independent Matrix of the system

    Returns:
        np.array: X (value of n variables in the system of equations)
    """
    M = np.column_stack((A, B))
    N = len(B)
    
    for m in range(N):
        piv = m
        large = abs(M[m, m])
        for i in range(m+1, N):
            if abs(M[i, m]) > large:
                largest = M[i, m]
                piv = i
        for i in range(N+1):
            M[m, i], M[piv, i] = M[piv, i], M[m, i]
            
        M[m, :] /= M[m, m]
        
        for i in range(m+1,N):
            M[i, :] -= M[i, m]*M[m, :]
            
    x = np.zeros(N, float)
    for m in range(N-1, -1, -1):
        x[m] = M[m, N]
        for i in range(m+1, N):
            x[m] -= M[m, i]*x[i]
    return np.array(x)

import numpy as np
A = np.array([[0., 1., 4., 1.], [3., 4., -1., -1.], [1., -4., 1., 5.], [2., -2., 1., 3.]])
B = np.array([[-4.], [3.], [9.], [7.]])
x = eligausspiv(A, B)
print(np.dot(A, x))

[-4.  3.  9.  7.]


## LU Factorization.

- For a matrix with $n$ rows, we need to define $n$ matrices $L_i$ with $i=1,\cdots,n$.

- Once these have been obtained, the problem consists of applying them to the augmented matrix and performing back substitution:

    $$L_n\cdots L_2\cdot L_1\cdot A=L_n\cdots L_2\cdot L_1\cdot V,$$

- Since the product $L_n\cdots L_2\cdot L_1\cdot A$ is always the same, it does not need to be recomputed if the value of $V$ changes. 
  
  
- In practice, however, one attempts to minimize the operations performed on $V$,  
  so that its values are used only for back substitution. 
  
  
- This is achieved by defining the matrices:

    $$L=L_1^{-1}L_2^{-1}\cdots L_n^{-1}\quad\text{and}\quad U=L_n\cdots L_2\cdot L_1\cdot A,$$

    which satisfy:

    $$L\cdot U =A,\quad\Rightarrow\quad L\cdot U\cdot X =V$$

- $U$, as we have seen, is an upper triangular matrix.  

- In principle, computing $L$ requires calculating the inverse of each of the elementary matrices and operating with them.

* But this is not necessary:  
<br>

    - the matrix $L$ is the lower triangular matrix whose columns are generated at each step when transforming the matrix $A$ into an upper triangular matrix, that is, when computing $U$. 


* The matrix $L$ is a lower triangular matrix, whereas the matrix $U$ is an upper triangular matrix.


* Therefore, each of them can be solved by substitution: backward substitution for $U$ and forward substitution for $L$.


* Specifically, we want to solve:

    $$L\cdot U\cdot X = V,$$

    which can be decomposed into:

    $$U\cdot X = Y$$

    and the problem:

    $$L\cdot Y =V.$$


---

In [9]:
def LU(A,V):
    """LU Factorization for AX = V (A = LU) system of equations.

    Args:
        A (np.array): Main system matrix
        V (np.array): Independent system matrix
    Returns:
        np.array: system solution
    """
    
    def factLU(A):
        N = len(A)
        L = np.zeros([N, N], float)
        U = np.copy(A)
        for m in range(N):
            L[m:N, m] = U[m:N, m]
            div = U[m, m]
            U[m, :] /= div
            for i in range(m + 1, N):
                mult = U[i, m]
                U[i, :] -= mult*U[m, :]
        return L, U
    
    L, U = factLU(A)
    N = len(V)
    y = np.empty(N, float)
    for m in range(N):
        y[m] = V[m]
        for i in range(m):
            y[m] -= L[m, i]*y[i]
        y[m] /= L[m, m]
    
    x = np.empty(N, float)
    for m in range(N-1, -1, -1):
        x[m] = y[m]
        for i in range(m+1, N):
            x[m] -= U[m, i]*x[i]
    return(x)



A = np.array([[2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]], float)
B = np.array([[-4], [3], [9], [7]], float)
x = LU(A, B)
print(x)
print(np.dot(A, x))

[ 2. -1. -2.  1.]
[-4.  3.  9.  7.]


In [10]:
def LUpiv(A, V):
    """Pivoting LU Factorization for AX = V (A = LU) system of equations.

    Args:
        A (np.array): Main system matrix
        V (np.array): Independent system matrix
    Returns:
        np.array: system solution
    """

    def factLUpiv(A):
        N = len(A)
        L = np.zeros([N, N], float)
        U = np.copy(A)
        P = np.empty(N, int)

        for m in range(N):
            L[m:N, m] = U[m:N, m]

            pivot = m
            largest = abs(U[m, m])
            for i in range(m + 1, N):
                if abs(U[i, m]) > largest:
                    largest = abs(U[i, m])
                    pivot = i

            for i in range(N):
                U[m, i], U[pivot, i] = U[pivot, i], U[m, i]
                L[m, i], L[pivot, i] = L[pivot, i], L[m, i]

            P[m] = pivot

            div = U[m, m]
            U[m, :] /= div

            for i in range(m + 1, N):
                mult = U[i, m]
                U[i, :] -= mult * U[m, :]

        return L, U, P

    L, U, P = factLUpiv(A)
    N = len(V)

    for m in range(N):
        pivot = P[m]
        V[m], V[pivot] = V[pivot], V[m]

    y = np.empty(N, float)
    for m in range(N):
        y[m] = V[m]
        for i in range(m):
            y[m] -= L[m, i] * y[i]
        y[m] /= L[m, m]

    x = np.empty(N, float)
    for m in range(N - 1, -1, -1):
        x[m] = y[m]
        for i in range(m + 1, N):
            x[m] -= U[m, i] * x[i]

    n = int((2 * N**3) / 3)
    print("Number of operations:", n)

    return x

A = np.array([[0, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]], float)

V = np.array([-4, 3, 9, 7], float)

x = LUpiv(A, V)
print(x)


Number of operations: 42
[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


## Matrix Inverse

- The inverse matrix is calculated as:  

    $$A^{-1} = \frac{1}{\det(A)} \left[C\right]^T$$

    where $C_{ij}$ is the cofactor of $A_{ij}$.

- However, its direct application is computationally expensive.

- Moreover, it entails rounding errors that can be non-negligible.

- In cases where it is necessary to compute it, the procedure is to solve the system:

    $$A \cdot A^{-1} = I$$

    by applying Gaussian elimination or LU decomposition to each of the columns of $A^{-1}$ and $I$.


In [ ]:
def inverse(A):
    m, n = np.shape(A)
    invA = np.zeros([m, n])
    for i in range(m):
        I = np.zeros([m, 1], float)
        I[i] = 1
        invA[:, i] += eligauss(A, I)[:, 0]
    return invA


A = np.array([[2, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]], float)

iA = inverse(A)

I = np.dot(A, iA)
print(I)
print()
print(I[2, 2])
print()

for i in range(4):
    for j in range(4):
        I[i, j] = round(I[i, j], 0)

print(I)

## Tridiagonal and Band Matrices

- In physics, it is very common to encounter systems of equations:

    $$A \cdot X = B,$$

    with $A$ being a tridiagonal matrix, that is:

    $$A = \left(
    \begin{array}{llllll}
    a_{11} & a_{12} &      &           &          &          \nonumber\\
    a_{21} & a_{22} & a_{23} &           &          &          \nonumber\\
          & a_{32} & a_{33} & a_{34}     &          &          \nonumber\\
          &        & \ddots & \ddots     & \!\!\!\ddots    &          \nonumber\\
          &        &        & a_{n-2n-1} & a_{n-1n-1} & a_{n-1n} \nonumber\\
          &        &        &           & a_{nn-1}  & a_{nn} \nonumber\\
    \end{array}\right)$$

    where all elements not shown are zero.

- For example, in the algorithm for defining cubic splines or, in general, in all those systems where only nearest-neighbor interactions exist.

- Tridiagonal problems are ideal for applying Gaussian elimination, and their algorithm can be simplified compared to the general case.

- The idea is that for a given step of Gaussian elimination (for a given row),  
  it is not necessary to traverse all other rows, only the next one.

- Similarly, in back substitution, the equation for the variable $x_n$ will only involve $x_{n+1}$.

- Band matrices are those in which:

$$a_{ij} = 0 \quad \text{if} \quad j < i - k_1 \quad || \quad j > i + k_2 \quad \text{with} \quad k_1, k_2 > 0.$$

- The algorithm to solve them will be the same as for tridiagonal matrices, but traversing in each step the next $k_1$ rows.


In [ ]:
def eligauss_tri(A, v):
    """Gauss Elimination for band matrix A.

    Args:
        A (np.array): Main Matrix of the system
        B (np.array): Independent Matrix of the system

    Returns:
        np.array: X (value of n variables in the system of equations)
    """
    N = len(v)

    for i in range(N - 1):
        A[i, i + 1] /= A[i, i]
        v[i] /= A[i, i]

        A[i + 1, i + 1] -= A[i + 1, i] * A[i, i + 1]
        v[i + 1] -= A[i + 1, i] * v[i]

    v[N - 1] /= A[N - 1, N - 1]

    x = np.zeros(N, float)
    x[N - 1] = v[N - 1]

    for i in range(N - 2, -1, -1):
        x[i] = v[i] - A[i, i + 1] * x[i + 1]

    return x

## Jacobi Method

- The Jacobi method is based on decomposing a matrix whose diagonal elements are nonzero (pivoting must be applied if not the case) into:

    $$A = D + L + U$$

    where $D$ is diagonal and $L/U$ has nonzero elements only below/above the diagonal.

- Therefore, the system of equations $A \cdot x = v$ can be written as

    $$A \cdot x = (D + L + U) \cdot x = v \quad \Rightarrow \quad D \cdot x = v - (L + U) \cdot x,$$

- Since $D$ has nonzero determinant, it is invertible and therefore:

    $$x = D^{-1} \left(v - (L + U) \cdot x\right) \quad \Rightarrow \quad x_i = \frac{1}{a_{ii}} \left(v_i - \sum_{j \neq i} {a_{ij} \, x_j}\right), \quad \text{with} \quad i = 1 \cdots N.$$

- Instead of seeking the exact solution, the equation allows for the development of an iterative method.

- Defining a starting point $x^{(0)}$, for example $x^{(0)} = 0$ if no other information is available, we obtain for the $k$-th estimate:

    $$x_i^{k+1} = \frac{1}{a_{ii}} \left(v_i - \sum_{j \neq i} {a_{ij} \, x_j^k}\right),$$

- However, the system will only converge if the condition is satisfied:

    $$\left\vert D^{-1} \cdot (L + U) \right\vert < 1 \quad \Rightarrow \quad a_{ii} > \sum_{j \neq i} \vert a_{ij} \vert.$$

---

In [ ]:
def jacobi(A, v, eps):
    """Jacobi's method for solving AX = v.

    Args:
        A (np.array): main system matrix
        v (np.array): independent system matrix
        eps (float): desired accuracy

    Returns:
        np.array: system solution
    """
    N = len(v)

    D = np.diag(A)
    LU = A - np.diagflat(D)

    x0 = np.zeros(N, float)
    err = 1e6
    it = 0
    while err > eps:
        x = (v - np.dot(LU, x0)) / D
        err = abs(max(x - x0))
        x0 = np.copy(x)
        it += 1
    print("Jacobi's method iterations:", it)
    return x

A = np.array([[8, 1, 2, 1],
              [1, 5, -1, -1],
              [1, -4, 6, 1],
              [1, -2, 1, 5]], float)

V = np.array([-1, 3, 2, 1], float)

x1 = jacobi(A, V, 1e-6)
print(x1)


## Gauss-Seidel Method

- This corresponds to a variation of the Jacobi method, based on the observation that the matrix $D + L$ is lower triangular and can therefore be solved by forward substitution:

    $$(L + D) \cdot x = v - U \cdot x,$$

- Therefore, starting from an initial estimate for $x$, we can solve the system exactly, which allows us to accelerate the convergence of the Jacobi method.

    $$x_i^{k+1} = \frac{1}{a_{ii}} \left(v_i - \sum_{j=1}^{i-1} {a_{ij} \, x_j^{k+1}} - \sum_{j=i+1}^{N} {a_{ij} \, x_j^k} \right),$$

    which converges if

    $$\left\vert (D + L)^{-1} \cdot U \right\vert < 1,$$

    conditions that are satisfied if $A$ is positive definite or diagonally dominant.

---

In [ ]:
def gauss_seidel(A, v, eps):
    """Gauss-Seidel's method for solving AX = v.

    Args:
        A (np.array): main system matrix
        v (np.array): independent system matrix
        eps (float): desired accuracy

    Returns:
        np.array: system solution
    """
    N = len(v)

    DL = np.tril(A)
    U = A - DL
    x0 = np.zeros(N, float)
    err = 1e6
    it = 0
    while err > eps:
        x = (v - np.dot(U, x0))
        for m in range(N):
            for i in range(m):
                x[m] -= DL[m, i] * x[i]
            x[m] /= DL[m, m]
        err = abs(max(x - x0))
        x0 = np.copy(x)
        it += 1
    print("Gauss-Seidel's method iterations:", it)
    return x


A = np.array([[8, 1, 2, 1],
              [1, 5, -1, -1],
              [1, -4, 6, 1],
              [1, -2, 1, 5]], float)

V = np.array([-1, 3, 2, 1], float)

x1 = gauss_seidel(A, V, 1e-6)
print(x1)

## Successive Over-Relaxation (SOR) Method

- The Gauss-Seidel method can be written as:

    $$x_i^{k+1} = x_i^k + \frac{1}{a_{ii}} \left(v_i - \sum_{j=1}^{i-1} {a_{ij} \, x_j^{k+1}} - \sum_{j=i}^{N} {a_{ij} \, x_j^k} \right),$$

    where we have simply added and subtracted the estimate $x^k$ in the solution.

- Relaxation methods use that the combination $D + \omega L$, with $\omega$ being an arbitrary parameter, is a lower triangular matrix to generalize the Gauss-Seidel method for the case $\omega \neq 0$:

    $$x_i^{k+1} = (1 - \omega) \, x_i^k + \frac{\omega}{a_{ii}} \left(v_i - \sum_{j=1}^{i-1} {a_{ij} \, x_j^{k+1}} - \sum_{j=i+1}^{N} {a_{ij} \, x_j^k} \right),$$

    which allows finding the value of $\omega$ that optimizes convergence.

- Moreover, for values $0 < \omega < 2$, the successive over-relaxation method converges for any symmetric positive definite matrix.

---


In [11]:
def relax(A, v, w, eps):
    N = len(v)
    DL = np.tril(A)
    U = A - DL
    x0 = np.zeros(N, float)

    err = 1e6
    it = 0

    while err > eps:
        x = (v - np.dot(U, x0))
        for m in range(N):
            for i in range(m):
                x[m] -= DL[m, i] * x[i]
            x[m] = (1 - w) * x0[m] + w / DL[m, m] * x[m]
        err = abs(max(x - x0))
        x0 = np.copy(x)
        it += 1
    print("SOR method iterations:", it)
    return x, it


A = np.array([[8, 1, 2, 1],
              [1, 5, -1, -1],
              [1, -4, 6, 1],
              [1, -2, 1, 5]], float)

V = np.array([-1, 3, 2, 1], float)

x1 = relax(A, V, 1.1, 1e-6)
print(x1)

SOR method iterations: 9
(array([-0.57409704,  1.02366121,  1.02490661,  0.51930259]), 9)


## QR Decomposition

- The most common method used to compute the eigenvalues of a matrix is the QR decomposition.

- It is similar to the $LU$ factorization, but in this case the matrix $A$ is decomposed as

    $$A = Q \cdot R,$$

    where $Q$ is an orthogonal matrix and $R$ is an upper triangular matrix.

- The QR factorization corresponds to applying the Gram-Schmidt method to obtain an orthonormal basis.

- To do this, consider the matrix $A$ as a set of $N$ column vectors $a_1, \cdots, a_N$

    $$A = \left(
    \begin{array}{cccc}
    \vert & \vert & \cdots & \vert \nonumber\\
    a_1 & a_2 & \cdots & a_n \nonumber\\
    \vert & \vert & \cdots & \vert \nonumber\\
    \end{array}\right)$$

    which we can use to construct the vectors $u_i$ and $q_i$ for $i = 1, \cdots, N$ defined by

    \begin{align}
    u_1 =&\, a_1, \quad &q_1 = \frac{u_1}{\vert u_1 \vert}, \nonumber\\
    u_2 =&\, a_2 - \left(q_1 \cdot a_2\right) \, q_1, \quad &q_2 = \frac{u_2}{\vert u_2 \vert}, \nonumber\\
    u_3 =&\, a_3 - \left(q_1 \cdot a_3\right) q_1 - \left(q_2 \cdot a_3\right) q_2, \quad &q_3 = \frac{u_3}{\vert u_3 \vert}, \nonumber\\
    \end{align}

    and in general

    $$u_i = a_i - \sum_{j=1}^{i-1} \left(a_j \cdot q_j \right) q_j, \quad q_i = \frac{u_i}{\vert u_i \vert},$$

- The vectors $q_i$ form a basis of orthonormal vectors, which allows writing:

    $$A = \left(
    \begin{array}{cccc}
    \vert & \vert & \cdots & \vert \nonumber\\
    a_1 & a_2 & \cdots & a_n \nonumber\\
    \vert & \vert & \cdots & \vert \nonumber\\
    \end{array}\right)
    = \left(
    \begin{array}{cccc}
    \vert & \vert & \cdots & \vert \nonumber\\
    q_1 & q_2 & \cdots & q_n \nonumber\\
    \vert & \vert & \cdots & \vert \nonumber\\
    \end{array}\right)
    \cdot
    \left(
    \begin{array}{cccc}
    \vert u_1 \vert & \left(q_1 \cdot a_2\right) & \cdots & \left(q_1 \cdot a_n\right) \nonumber\\
    0 & \vert u_2 \vert & \cdots & \left(q_2 \cdot a_n\right) \nonumber\\
    \vdots & \vdots & \ddots & \vdots \nonumber\\
    \end{array}\right)
    = Q \cdot R$$

---

### Successive QR Decompositions

- Once we have factorized our matrix $A$ into an orthogonal matrix $Q_1$ and an upper triangular matrix $R_1$

    $$A = Q_1 \cdot R_1,$$

    multiplying $Q_1$ on the right and $Q_1^T$ on the left gives

    $$Q_1^T \cdot A \cdot Q_1 = Q_1^T \cdot Q_1 \cdot R_1 \cdot Q_1 = R_1 \cdot Q_1,$$

    using the fact that $Q_1$ is orthogonal.

- Calling $A_1 = Q_1^T \cdot A \cdot Q_1$, it is important to note that $A$ and $A_1$ have the same eigenvalues (same spectrum) and are therefore similar matrices.

- Calling $v_1$ and $\lambda_1$ one of the eigenvectors and eigenvalues of $A_1$, we have

    $$A_1 \cdot v_1 = Q_1^T \cdot A \cdot Q_1 \cdot v_1 = \lambda_1 \, v_1 \Rightarrow A \cdot (Q_1 \cdot v_1) = \lambda_1 (Q_1 \cdot v_1),$$

    and therefore $\lambda_1$ is also an eigenvalue of $A$ with eigenvector $Q_1 \cdot v_1$.

- This implies that the eigenvalue problem remains the same, and we can focus on the new matrix $A_1$, which can be further decomposed as

    $$A_1 = Q_1^T \cdot A \cdot Q_1 = Q_2 \cdot R_2,$$

    and multiplying again by $Q_2$ and $Q_2^T$ on the right and left, we obtain a new matrix $A_2$

    $$A_2 = Q_2^T \cdot A_1 \cdot Q_2 = Q_2^T \cdot Q_1^T \cdot A \cdot Q_1 \cdot Q_2 = R_2 \cdot Q_2.$$

- We can repeat this process $n$ times, obtaining at each iteration:

    \begin{align}
    A_1 =&\, Q_1^T \cdot A \cdot Q_1, \nonumber\\
    A_2 =&\, Q_2^T \cdot Q_1^T \cdot A \cdot Q_1 \cdot Q_2, \nonumber\\
    A_3 =&\, Q_3^T \cdot Q_2^T \cdot Q_1^T \cdot A \cdot Q_1 \cdot Q_2 \cdot Q_3, \nonumber\\
    \vdots \quad & \quad \quad \quad \quad \vdots, \nonumber\\
    A_n =&\, (Q_n^T \cdots Q_1^T) \cdot A \cdot (Q_1 \cdots Q_n), \nonumber\\
    \end{align}

- An orthogonal matrix is simply a change of coordinates, i.e., a rotation.

- For example, in two dimensions, $N = 2$:

    $$Q = \left(
    \begin{array}{cc}
    \cos \alpha & -\sin \alpha \nonumber\\
    \sin \alpha & \cos \alpha \nonumber\\
    \end{array}\right),$$

- Rotating the coordinate system of our matrix $k$ times transforms the matrix into a diagonal matrix.

- The proof that in the limit as $k \to \infty$ this is the case is complicated, but it can be understood by noting that while off-diagonal elements involve the product of sines and cosines, the diagonal elements always sum squares of sines and cosines.

- Therefore, the idea is to continue the process until the matrix $A_k$ becomes diagonal.

- The off-diagonal terms become progressively smaller until they are zero or close enough to zero to be neglected.

- Thus, given a desired precision, we can diagonalize the matrix through similarity transformations until obtaining a diagonal matrix.

- Defining the orthogonal matrix:

    $$V = \left(Q_1 \cdots Q_n\right) = \prod_{i=1}^k Q_i,$$

    we obtain:

    $$V^T \cdot A \cdot V = D \;\Rightarrow\; A \cdot V = D \cdot V.$$

---

Given a precision $\epsilon$ for the off-diagonal terms:

1. Create an $N \times N$ matrix $V$ to store the eigenvectors. Initialize $V$ as the identity matrix.

2. Compute the QR factorization of $A$: $A = Q \cdot R$.

3. Update $A$ to a new value: $A = R \cdot Q$.

4. Multiply $V$ on the right by $Q$.

5. Check the off-diagonal terms of the new $A$. If their absolute values are less than $\epsilon$, the process is complete. Otherwise, return to step 2.

---

In [12]:
def module(v):
    """Module of a vector v.

    Args:
        v (np.array): 1-D array.

    Returns:
        np.array: module of argument vector
    """
    return np.sqrt(np.dot(v, v))


def QR(A, eps):
    """QR factorization of matrix A with accuracy eps

    Args:
        A (np.arrayt): matrix to factorize
        eps (float): desired accuracy

    Returns:
        np.array: two matrices corresponding to A's QR factorization
    """
    N = len(A)

    def QR_factorization(A):
        N = len(A)
        U = np.zeros([N, N], float)
        Q = np.zeros([N, N], float)
        R = np.zeros([N, N], float)

        for m in range(N):
            U[:, m] = A[:, m]
            for i in range(m):
                R[i, m] = np.dot(Q[:, i], A[:, m])
                U[:, m] -= R[i, m] * Q[:, i]
            R[m, m] = module(U[:, m])
            Q[:, m] = U[:, m] / R[m, m]
        return Q, R

    V = np.identity(N, float)
    delta = 1.0
    while delta > eps:
        Q, R = QR_factorization(A)
        A = np.dot(R, Q)
        V = np.dot(V, Q)
        Ac = np.copy(A)
        for i in range(N):
            Ac[i, i] = 0.0
        delta = np.max(np.absolute(Ac))
    for i in range(len(Q)):
        for j in range(len(Q)):
            A[i, j] = int(round(A[i, j]))
    return A, V


A = np.array([[1, 4, 8, 4],
              [4, 2, 3, 7],
              [8, 3, 6, 9],
              [4, 7, 9, 2]], float)

D, V = QR(A, 1e-6)
print(D)
print()
print(V)

[[21.  0.  0.  0.]
 [ 0. -8.  0.  0.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0.  1.]]

[[ 0.43151698 -0.38357064 -0.77459666 -0.25819889]
 [ 0.38357063  0.43151698 -0.2581989   0.77459667]
 [ 0.62330228  0.52740965  0.25819889 -0.51639778]
 [ 0.52740965 -0.62330227  0.51639779  0.25819889]]
