In [16]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Métodos de Resolución de Ecuaciones Lineales.

- Queremos resolver numéricamente un sistema de $n$ ecuaciones lineales con $n$ incógnitas de la forma:

    \begin{align}
    a_{11}\,x_1+a_{12}\,x_2+\cdots+a_{1n}\,x_n &= b_1,\nonumber\\
    a_{21}\,x_1+a_{22}\,x_2+\cdots+a_{2n}\,x_n &= b_2,\nonumber\\
    \vdots\quad\qquad\vdots\qquad\qquad\vdots\quad&\quad\vdots\nonumber\\
    a_{n1}\,x_1+a_{n2}\,x_2+\cdots+a_{nn}\,x_n &=b_n,\nonumber\\
    \end{align}

    o en formulación matricial:

    $$A\cdot X =B,$$

    con

$$A=\left(
\begin{array}{cccc}
a_{11}&a_{12}&\cdots&a_{1n}\nonumber\\
a_{21}&a_{22}&\cdots&a_{2n}\nonumber\\
\vdots&\vdots&\ddots&\vdots\nonumber\\
a_{n1}&a_{n2}&\cdots&a_{nn}\nonumber\\
\end{array}\right),\quad
X=\left(
\begin{array}{c}
x_1\nonumber\\
x_2\nonumber\\
\vdots\nonumber\\
x_n\nonumber\\
\end{array}
\right)\quad\text{y}\quad B=\left(
\begin{array}{c}
b_1\nonumber\\
b_2\nonumber\\
\vdots\nonumber\\
b_n\nonumber\\
\end{array}
\right).
$$
<br/>

---

## Eliminación Gaussiana.

- La idea del método es utilizar operaciones elementales de matrices que permitan transformar nuestro sistema de ecuaciones inicial en uno donde la matriz $A$ sea triangular.


- Para ello construimos en primer lugar la matriz ampliada:

$$\left(A\vert B\right)=\left(
\begin{array}{cccccc}
a_{11}&a_{12}&\cdots&a_{1n}&\vert& b_1\nonumber\\
a_{21}&a_{22}&\cdots&a_{2n}&\vert& b_2\nonumber\\
\vdots&\vdots&\ddots&\vdots&\vert &\vdots\nonumber\\
a_{n1}&a_{n2}&\cdots&a_{nn}&\vert& b_n\nonumber\\
\end{array}\right)$$

- Operaciones elementales sobre la matriz extendida:

    1. Multiplicar una fila por un escalar (no nulo).
    2. Sumar a una fila el múltiplo de otra. 
    3. Intercambiar las posición de dos filas.
    
    
- El método de Gauss combina las operaciones 1 y 2 para transformar:

    $$\left(A\vert B\right)=\left(
    \begin{array}{ccccccc}
    a_{11}&a_{12}&a_{31}&\cdots&a_{1n}&\vert& b_1\nonumber\\
    a_{21}&a_{22}&a_{32}&\cdots&a_{2n}&\vert& b_2\nonumber\\
    a_{31}&a_{32}&a_{33}&\cdots&a_{3n}&\vert& b_3\nonumber\\
    \vdots&\vdots&\vdots&\ddots&\vdots&\vert &\vdots\nonumber\\
    a_{n1}&a_{n2}&a_{n3}&\cdots&a_{nn}&\vert& b_n\nonumber\\
    \end{array}\right)\quad\Rightarrow\quad 
    \left(
    \begin{array}{ccccccc}
     1 &\bar a_{12}&\bar a_{31}&\cdots&\bar a_{1n}&\vert&\bar b_1\nonumber\\
    0& 1&\bar a_{32}&\cdots&\bar a_{2n}&\vert&\bar b_2\nonumber\\
    0&0& 1 &\cdots&\bar a_{3n}&\vert&\bar b_3\nonumber\\
    \vdots&\vdots&\vdots&\ddots&\vdots&\vert &\vdots\nonumber\\
    0&0&0&\cdots& 1 &\vert&\bar b_n\nonumber\\
    \end{array}\right)$$

    donde el segundo sistema de ecuaciones se puede resolver por sustitución inversa.

**¿Cómo podemos obtener la matriz triangular?** 

- Dividimos la **primera** fila por el **primer** elemento $a_{11}$.
- Le restamos a la fila $j>1$ la primera fila multiplicada por su primer elemento $a_{j1}$. 
- Dividimos la **segunda** fila por su **segundo** elemento $a_{22}$. 
- Le restamos a la fila $j>2$ la segunda fila multiplicada por su primer elemento $a_{j2}$. 
- Continuamos de la misma fórmula hasta llegar al último elemento.

**¿Cómo realizar la sustitución hacía atrás?** 
- El valor de $x_n=\bar b_n$
- El valor de $x_{n-1}=\bar b_{n-1} -\bar a_{n-1,n} x_n$
- Continuamos restándole a las filas anteriores el valor de todas las incógnitas que acabamos de resolver multiplicadas por su correspondiente coeficiente en la fila.

---

In [17]:
def eligauss(A,B):
    """Gaussian Elimination for AX = B.

    Args:
        A (np.array): Main Matrix of the system
        B (np.array): Independent Matrix of the system

    Returns:
        np.array: X (value of n variables in the system of equations)
    """

    M = np.column_stack((A, B))
    N = len(B)
    
    for i in range(N):
        M[i, :] /= M[i, i]
        for j in range(i+1, N):
            M[j] -= M[j, i]*M[i, :]
            
    x = np.zeros([N, 1], float)
    for k in range(N-1, -1, -1):
        x[k] = M[k, N]
        for s in range(k+1, N):
            x[k] -= M[k, s]*x[s]
    return np.array(x)

A = np.array([[2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]], float)
B = np.array([[-4], [3], [9], [7]], float)
eligauss(A, B)

array([[ 2.],
       [-1.],
       [-2.],
       [ 1.]])

## Método del pivote.

- La eliminación gaussiana requiere dividir en cada paso por el elemento $a_{ii}$, lo cual sólo es posible si el elemento es diferente de cero.


- El método del pivote combina la eliminación gaussiana con la operación elemental 3 de las matrices:   
  el intercambio de una fila por otro. 


- Esto garantiza que en ningún paso un elemento de la diagonal sea 0.


- No hay una única forma de hacerlo. 


- La regla general es intercambiar en cada paso la fila $m$ por la fila $j>m$ tal que $\vert a_{jm}\vert$ tenga el valor máximo de todos los $a_{km}$  con $m\le k\le n$.

---

In [18]:
def eligausspiv(A,B):
    """Pivoting Gaussian Elimination for AX = B.

    Args:
        A (np.array): Main Matrix of the system
        B (np.array): Independent Matrix of the system

    Returns:
        np.array: X (value of n variables in the system of equations)
    """
    M = np.column_stack((A, B))
    N = len(B)
    
    for m in range(N):
        piv = m
        large = abs(M[m, m])
        for i in range(m+1, N):
            if abs(M[i, m]) > large:
                largest = M[i, m]
                piv = i
        for i in range(N+1):
            M[m, i], M[piv, i] = M[piv, i], M[m, i]
            
        M[m, :] /= M[m, m]
        
        for i in range(m+1,N):
            M[i, :] -= M[i, m]*M[m, :]
            
    x = np.zeros(N, float)
    for m in range(N-1, -1, -1):
        x[m] = M[m, N]
        for i in range(m+1, N):
            x[m] -= M[m, i]*x[i]
    return np.array(x)

import numpy as np
A = np.array([[0., 1., 4., 1.], [3., 4., -1., -1.], [1., -4., 1., 5.], [2., -2., 1., 3.]])
B = np.array([[-4.], [3.], [9.], [7.]])
x = eligausspiv(A, B)
print(np.dot(A, x))

[-4.  3.  9.  7.]


## Factorización LU.

- Para una matriz con $n$ filas, necesitamos definir $n$ matrices $L_i$ con $i=1,\cdots,n$.


- Una vez obtenidas el problema reside en operar con ellas sobre la matriz extendida y realizar la sustitución hacía atrás:

    $$L_n\cdots L_2\cdot L_1\cdot A=L_n\cdots L_2\cdot L_1\cdot V,$$


- Puesto que el producto $L_n\cdots L_2\cdot L_1\cdot A$ siempre es el mismo, no hace falta volverlo a calcular si se cambia el valor de V. 
  
  
- En la práctica sin embargo se intenta minimizar las operaciones sobre V,  
  de forma que sus valores sólo se utilizan para la sustitución hacía atrás. 
  
  
- Ello se consigue definiendo la matrices:

    $$L=L_1^{-1}L_2^{-1}\cdots L_n^{-1}\quad\text{y}\quad U=L_n\cdots L_2\cdot L_1\cdot A,$$

    que satisfacen que:

    $$L\cdot U =A,\quad\Rightarrow\quad L\cdot U\cdot X =V$$


- $U$, tal y como hemos visto, es una matriz triangular superior.  


- En principio el cálculo de $L$ requiere calcular la inversa de cada una de las matrices elementales y operar con ellas.

* Pero no es necesario: 
<br>

    - la matriz L es la matriz triangular cuyas columnas se generan en cada paso al convertir la matriz A en una matriz triangular superior, es decir, cuando se calcula U. 


* La matriz L es una matriz diagonal inferior mientras que la matriz U es una matriz diagonal superior.


* Por tanto, cada una de ellas puede resolverse por medio de la sustitución, hacía atrás para U y hacía adelante para L.


* Específicamente, queremos resolver:

    $$L\cdot U\cdot X = V,$$

    que se puede descomponer en:

    $$U\cdot X = Y$$

    y el problema:

    $$L\cdot Y =V.$$

---

In [19]:
def LU(A,V):
    """LU Factorization for AX = V (A = LU) system of equations.

    Args:
        A (np.array): Main system matrix
        V (np.array): Independent system matrix
    Returns:
        np.array: system solution
    """
    
    def factLU(A):
        N = len(A)
        L = np.zeros([N, N], float)
        U = np.copy(A)
        for m in range(N):
            L[m:N, m] = U[m:N, m]
            div = U[m, m]
            U[m, :] /= div
            for i in range(m + 1, N):
                mult = U[i, m]
                U[i, :] -= mult*U[m, :]
        return L, U
    
    L, U = factLU(A)
    N = len(V)
    y = np.empty(N, float)
    for m in range(N):
        y[m] = V[m]
        for i in range(m):
            y[m] -= L[m, i]*y[i]
        y[m] /= L[m, m]
    
    x = np.empty(N, float)
    for m in range(N-1, -1, -1):
        x[m] = y[m]
        for i in range(m+1, N):
            x[m] -= U[m, i]*x[i]
    return x



A = np.array([[2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]], float)
B = np.array([[-4], [3], [9], [7]], float)
x = LU(A, B)
print(x)
print(np.dot(A, x))

[ 2. -1. -2.  1.]
[-4.  3.  9.  7.]


In [20]:
def LUpiv(A, V):
    """Pivoting LU Factorization for AX = V (A = LU) system of equations.

    Args:
        A (np.array): Main system matrix
        V (np.array): Independent system matrix
    Returns:
        np.array: system solution
    """

    def factLUpiv(A):
        N = len(A)
        L = np.zeros([N, N], float)
        U = np.copy(A)
        P = np.empty(N, int)

        for m in range(N):
            L[m:N, m] = U[m:N, m]

            pivot = m
            largest = abs(U[m, m])
            for i in range(m + 1, N):
                if abs(U[i, m]) > largest:
                    largest = abs(U[i, m])
                    pivot = i

            for i in range(N):
                U[m, i], U[pivot, i] = U[pivot, i], U[m, i]
                L[m, i], L[pivot, i] = L[pivot, i], L[m, i]

            P[m] = pivot

            div = U[m, m]
            U[m, :] /= div

            for i in range(m + 1, N):
                mult = U[i, m]
                U[i, :] -= mult * U[m, :]

        return L, U, P

    L, U, P = factLUpiv(A)
    N = len(V)

    for m in range(N):
        pivot = P[m]
        V[m], V[pivot] = V[pivot], V[m]

    y = np.empty(N, float)
    for m in range(N):
        y[m] = V[m]
        for i in range(m):
            y[m] -= L[m, i] * y[i]
        y[m] /= L[m, m]

    x = np.empty(N, float)
    for m in range(N - 1, -1, -1):
        x[m] = y[m]
        for i in range(m + 1, N):
            x[m] -= U[m, i] * x[i]

    n = int((2 * N**3) / 3)
    print("Number of operations:", n)

    return x

A = np.array([[0, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]], float)

V = np.array([-4, 3, 9, 7], float)

x = LUpiv(A, V)
print(x)


Number of operations: 42
[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


## Inversa de una Matriz.

- La matriz de inversa se calcula como:   
   
    $$A^{-1}=\frac{1}{\det(A)}\left[C\right]^T$$

    con $C_{ij}$ el cofactor de $A_{ij}$.


- Sin embargo su aplicación directa es computacionalmente pesada.


- Además, conlleva errores de redondeo que pueden ser no despreciables. 


- En aquellos casos donde sea necesario calcularla el procedimiento es resolver el sistema:

    $$A\cdot A^{-1}=I$$

    aplicando la eliminación gaussiana o la descomposición LU a cada una de las columnas de $A^{-1}$ y de $I$.

---

In [21]:
def inverse(A):
    m, n = np.shape(A)
    invA = np.zeros([m, n])
    for i in range(m):
        I = np.zeros([m, 1], float)
        I[i] = 1
        invA[:, i] += eligauss(A, I)[:, 0]
    return invA


A = np.array([[2, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]], float)

iA = inverse(A)

I = np.dot(A, iA)
print(I)
print()
print(I[2, 2])
print()

for i in range(4):
    for j in range(4):
        I[i, j] = round(I[i, j], 0)

print(I)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  2.22044605e-16 -2.22044605e-16  1.00000000e+00]]

0.9999999999999998

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -0.  1.  0.]
 [-0.  0. -0.  1.]]


## Matrices tridiagonales y matrices banda.

- En física es muy común encontrar sistemas de ecuaciones:

    $$A\cdot X=B,$$

    con A siendo una matriz tridiagonal, es decir:

    $$A=\left(
    \begin{array}{llllll}
    a_{11}&a_{12}&      &           &          &          \nonumber\\
    a_{21}&a_{22}&a_{23}&           &          &          \nonumber\\
          &a_{32}&a_{33}&a_{34}     &          &          \nonumber\\
          &      &\ddots&\ddots     &\!\!\!\ddots    &          \nonumber\\
          &      &      & a_{n-2n-1}&a_{n-1n-1}&a_{n-1n} \nonumber\\
          &      &      &           &a_{nn-1}  &a_{nn}\nonumber\\
    \end{array}\right)$$

    donde todos los elementos que no aparecen son cero.


- Por ejemplo en el algoritmo para definir los splines cúbicos o en general en todos aquellos sistemas donde sólo hay interacciones entre vecinos. 


- Los problemas tridiagonales son perfectos para aplicar la eliminación gaussiana, y su algoritmo pueden simplificarse con respecto al general.


- La idea es que para un paso dado de la eliminación gaussiana (para una fila dada),   
  no es necesario recorrer todas las demás, sólo la siguiente. 


- De la misma forma en la sustitución hacía atrás, la ecuación para la variable $x_n$ sólo involucrará a $x_{n+1}$.


- Las matrices banda son aquellas en las que:

$$a_{ij}=0\quad\text{si}\quad j<i-k_1\quad||\quad j>i+k_2\quad \text{con}\quad k_1, k_2>0.$$


- El algoritmo para resolverlas será igual al de las matrices tridiagonales pero recorriendo en cada paso las $k_1$ filas siguientes.  

---

In [22]:
def eligauss_tri(A, v):
    """Gauss Elimination for tridiagonal matrix A.

    Args:
        A (np.array): Main Matrix of the system
        B (np.array): Independent Matrix of the system

    Returns:
        np.array: X (value of n variables in the system of equations)
    """
    N = len(v)

    for i in range(N - 1):
        A[i, i + 1] /= A[i, i]
        v[i] /= A[i, i]

        A[i + 1, i + 1] -= A[i + 1, i] * A[i, i + 1]
        v[i + 1] -= A[i + 1, i] * v[i]

    v[N - 1] /= A[N - 1, N - 1]

    x = np.zeros(N, float)
    x[N - 1] = v[N - 1]

    for i in range(N - 2, -1, -1):
        x[i] = v[i] - A[i, i + 1] * x[i + 1]

    return x


import numpy as np


def eligauss_band(A, v, up, down):
    """Gauss Elimination for band matrix A.

    Args:
        A (np.array): Main Matrix of the system
        B (np.array): Independent Matrix of the system

    Returns:
        np.array: X (value of n variables in the system of equations)
    """
    N = len(v)

    for m in range(N):
        div = A[up, m]
        v[m] /= div
        for k in range(1, down + 1):
            if m + k < N:
                v[m + k] -= A[up + k, m] * v[m]

        for i in range(up):
            j = m + up - i
            if j < N:
                A[i, j] /= div
                for k in range(1, down + 1):
                    A[i + k, j] -= A[up + k, m] * A[i, j]

    for m in range(N - 2, -1, -1):
        for i in range(up):
            j = m + up - i
            if j < N:
                v[m] -= A[i, j] * v[j]

    return v



## Método de Jacobi.


- El método de Jacobi se basa en descomponer una matriz cuyos elementos diagonales no sean nulos (hay que aplicar el pivote si no es el caso) en:

    $$A=D+L+U$$

    donde $D$ es diagonal y $L/U$ sólo tiene elementos no nulos por debajo/encima de la diagonal.


- Por tanto el sistema de ecuaciones $A\cdot x=v$ se puede escribir como

$$A\cdot x=(D+L+U)\cdot x =v\quad\Rightarrow\quad D\cdot x =v-(L+U)\cdot x,$$


- Como D no tiene determinante nulo, es invertibles y por tanto:

$$x =D^{-1}\left(v-(L+U)\cdot x\right)\quad\Rightarrow\quad x_i=\,\frac{1}{a_{ii}}\left(v_i-\sum_{j\neq i}{a_{ij}\,x_j}\right),\quad\text{con}\quad i=1\cdots N.$$


- En vez de buscar la solución exacta, la ecuación permite desarrollar un método iterativo.


- Definiendo un punto de partida $x^{(0)}$, por ejemplo $x^{(0)}=0$ si no hay más información, obtenemos para la estimación $k$-esima es:

$$x_i^{k+1}=\,\frac{1}{a_{ii}}\left(v_i-\sum_{j\neq i}{a_{ij}\,x_j^k}\right),$$


- Sin embargo el sistema sólo convergerá si se cumple la condición:

$$\left\vert\, D^{-1}\cdot(L+U)\,\right\vert <1\quad\Rightarrow\quad a_{ii} > \sum_{j\neq i} \vert a_{ij}\vert.$$

---

In [23]:
def jacobi(A, v, eps):
    """Jacobi's method for solving AX = v.

    Args:
        A (np.array): main system matrix
        v (np.array): independent system matrix
        eps (float): desired accuracy

    Returns:
        np.array: system solution
    """
    N = len(v)

    D = np.diag(A)
    LU = A - np.diagflat(D)

    x0 = np.zeros(N, float)
    err = 1e6
    it = 0
    while err > eps:
        x = (v - np.dot(LU, x0)) / D
        err = abs(max(x - x0))
        x0 = np.copy(x)
        it += 1
    print("Jacobi's method iterations:", it)
    return x

A = np.array([[8, 1, 2, 1],
              [1, 5, -1, -1],
              [1, -4, 6, 1],
              [1, -2, 1, 5]], float)

V = np.array([-1, 3, 2, 1], float)

x1 = jacobi(A, V, 1e-6)
print(x1)



Jacobi's method iterations: 25
[-0.57409676  1.02366086  1.02490595  0.51930229]


## Método de Gauss-Seidel.

- Corresponde a una variación del método de Jacobi, consistente en notar que la matriz D+L, es triangular inferior y por tanto se puede resolver por sustitución hacía adelante:

$$(L+D)\cdot x= v-U\cdot x,$$


- Por tanto, partiendo de una estimación inicial para x, podemos resolver el sistema exactamente, lo que nos permite acelerar la convergencia del método de jacobi.

    $$x_i^{k+1}=\,\frac{1}{a_{ii}}\left(v_i-\sum_{j=1}^{i-1}{a_{ij}\,x_j^{k+1}}-\sum_{j=i+1}^{N}{a_{ij}\,x_j^{k}}\right),$$

    que converge si

    $$\left\vert\, (D+L)^{-1}\cdot U\, \right\vert<1,$$

    condiciones que se cumplen si A es positiva definida o dominada por los elementos de la diagonal. 

---

In [24]:
def gauss_seidel(A, v, eps):
    """Gauss-Seidel's method for solving AX = v.

    Args:
        A (np.array): main system matrix
        v (np.array): independent system matrix
        eps (float): desired accuracy

    Returns:
        np.array: system solution
    """
    N = len(v)

    DL = np.tril(A)
    U = A - DL
    x0 = np.zeros(N, float)
    err = 1e6
    it = 0
    while err > eps:
        x = (v - np.dot(U, x0))
        for m in range(N):
            for i in range(m):
                x[m] -= DL[m, i] * x[i]
            x[m] /= DL[m, m]
        err = abs(max(x - x0))
        x0 = np.copy(x)
        it += 1
    print("Gauss-Seidel's method iterations:", it)
    return x


A = np.array([[8, 1, 2, 1],
              [1, 5, -1, -1],
              [1, -4, 6, 1],
              [1, -2, 1, 5]], float)

V = np.array([-1, 3, 2, 1], float)

x1 = gauss_seidel(A, V, 1e-6)
print(x1)


Gauss-Seidel's method iterations: 12
[-0.57409671  1.0236609   1.0249064   0.51930242]


## Método de Sobrerelajación sucesiva.

- El método de Gauss-Seidel se puede escribir como:

    $$x_i^{k+1}=x_i^k+\,\frac{1}{a_{ii}}\left(v_i-\sum_{j=1}^{i-1}{a_{ij}\,x_j^{k+1}}-\sum_{j=i}^{N}{a_{ij}\,x_j^{k}}\right),$$

    donde simplemente hemos sumado y restado la estimación $x^k$ en la solución.


- Los métodos de relajación usan que la combinación $D+\omega L$, siendo $\omega$ un parámetro arbitrario, es una matriz triangular inferior para generalizar el método de Gauss-Seidel para el caso $\omega\neq0$:

    $$x_i^{k+1}=(1-\omega)\,x_i^k+\,\frac{\omega}{a_{ii}}\left(v_i-\sum_{j=1}^{i-1}{a_{ij}\,x_j^{k+1}}-\sum_{j=i+1}^{N}{a_{ij}\,x_j^{k}}\right),$$

    que permite encontrar el valor de $\omega$ que optimiza la convergencia.


- Además, para valores de $0<\omega<2$ el método de sobrerelajación sucesiva converge para cualquier matriz simétrica definida positiva. 

---

In [25]:
def relax(A, v, w, eps):
    N = len(v)
    DL = np.tril(A)
    U = A - DL
    x0 = np.zeros(N, float)

    err = 1e6
    it = 0

    while err > eps:
        x = (v - np.dot(U, x0))
        for m in range(N):
            for i in range(m):
                x[m] -= DL[m, i] * x[i]
            x[m] = (1 - w) * x0[m] + w / DL[m, m] * x[m]
        err = abs(max(x - x0))
        x0 = np.copy(x)
        it += 1
    print("SOR method iterations:", it)
    return x, it


A = np.array([[8, 1, 2, 1],
              [1, 5, -1, -1],
              [1, -4, 6, 1],
              [1, -2, 1, 5]], float)

V = np.array([-1, 3, 2, 1], float)

x1 = relax(A, V, 1.1, 1e-6)
print(x1)


SOR method iterations: 9
(array([-0.57409704,  1.02366121,  1.02490661,  0.51930259]), 9)


## Descomposición QR.

- El método más común usado para calcular los autovalores de una matriz es la descomposición QR. 


- Es parecida a la factorización $LU$, pero en este caso la matriz $A$ se descompone como

    $$A=Q\cdot R,$$

    siendo $Q$ una matriz ortogonal y $R$ una matriz triangular superior. 


- La factorización QR corresponde a aplicar el método de Gramm-Schmidt para la obtención de una base ortonormal.


- Para ello entendamos la matriz A como un conjunto de $N$ vectores columna $a_1,\cdots,a_N$

    $$A=\left(
    \begin{array}{cccc}
    \vert&\vert&\cdots&\vert\nonumber\\
    a_{1}&a_{2}&\cdots&a_{n}\nonumber\\
    \vert&\vert&\cdots&\vert\nonumber\\
    \end{array}\right)$$

    que podemos usar para construir los vectores $u_i$ y $q_i$ con $i=1,\cdots,N$ definidos por

    \begin{align}
    u_1=&\,a_1,\quad &q_1=\frac{u_1}{\vert u_1\vert},\nonumber\\
    u_2=&\,a_2-\left(q_1\cdot a_2\right)\,q_1,\quad &q_2=\frac{u_2}{\vert u_2\vert},\nonumber\\
    u_3=&\,a_3-\left(q_1\cdot a_3\right)\,q_1-\left(q_2\cdot a_3\right)\,q_2,\quad &q_3=\frac{u_3}{\vert u_3\vert},\nonumber\\
    \end{align}

    y de forma general

    $$u_i=a_i-\sum_{j=1}^{i-1} \left(a_j\cdot q_j\right)q_j,\quad q_i=\frac{u_i}{\vert u_i\vert},$$


* Los vectores $q_i$ forma una base de vectores ortonormales, que permiten escribir:

$$A=\left(
\begin{array}{cccc}
\vert&\vert&\cdots&\vert\nonumber\\
a_{1}&a_{2}&\cdots&a_{n}\nonumber\\
\vert&\vert&\cdots&\vert\nonumber\\
\end{array}\right)=\left(
\begin{array}{cccc}
\vert&\vert&\cdots&\vert\nonumber\\
q_{1}&q_{2}&\cdots&q_{n}\nonumber\\
\vert&\vert&\cdots&\vert\nonumber\\
\end{array}\right)\cdot \left(
\begin{array}{cccc}
\vert u_{1}\vert &\left(q_1\cdot a_{2}\right)&\cdots&\left(q_1\cdot a_{n}\right)\nonumber\\
0&\vert u_{2}\vert &\cdots&\left(q_2\cdot a_{n}\right)\nonumber\\
\vdots&\vdots&\ddots&\vdots\nonumber\\
\end{array}\right)=Q\cdot R$$

---

### Descomposiciones QR sucesivas.

- Una vez hemos factorizado nuestra matriz A en una matriz ortogonal $Q_1$ y una matriz triangular $R_1$

    $$A=Q_1\cdot R_1,$$

    multiplicando $Q_1$ por la derecha y por $Q_1^T$ por la izquierda tenemos

    $$Q_1^T\cdot A\cdot Q_1=Q_1^T\cdot Q_1\cdot R_1\cdot Q_1=R_1\cdot Q_1,$$

    donde hemos usado que $Q_1$ es una matriz ortogonal.


- Llamando  $A_1=Q_1^T\cdot A\cdot Q_1$, lo relevante es notar que $A$ y $A_1$ tienen los mismos autovalores (el mismo espectro) y son por tanto matrices semejantes.


- Llamando $v_1$ y $\lambda_1$ a uno de los autovectores y autovalores de $A_1$ tenemos que

    $$A_1\cdot v_1=Q_1^T\cdot A\cdot Q_1\cdot v_1=\lambda_1\,v_1\Rightarrow A\cdot \left(Q_1\cdot v_1\right)= \lambda_1\left(Q_1\cdot v_1\right),$$

    y por tanto $\lambda_1$ también es un autovalor de $A$ con autovector $Q_1\cdot v_1$. 


- Esto implica que el problema de autovalores sigue siendo el mismo, y por tanto nos podemos centrar en la nueva matriz $A_1$, la cual podemos descomponer una vez más

    $$A_1=Q_1^T\cdot A\cdot Q_1=Q_2\cdot R_2,$$

    y volviendo a multiplicar por $Q_2$ y $Q_2^T$ por la derecha e izquierda respectivamente, encontramos una nueva matriz $A_2$

    $$A_2=Q_2^T\cdot A_1\cdot Q_2=Q_2^T\cdot Q_1^T\cdot A\cdot Q_1\cdot Q_2=R_2\cdot Q_2,$$


- Podemos repetir este proceso $n$ veces obteniendo en cada iteración:

    \begin{align}
    A_1=&\,Q_1^T\cdot A\cdot Q_1,\nonumber\\
    A_2=&\,Q_2^T\cdot Q_1^T\cdot A\cdot Q_1\cdot Q_2,\nonumber\\
    A_3=&\,Q_3^T\cdot Q_2^T\cdot Q_1^T\cdot A\cdot Q_1\cdot Q_2\cdot Q_3,\nonumber\\
    \vdots\quad &\quad\quad\quad\quad \vdots,\nonumber\\
    A_n=&\,\left(Q_n^T\cdots Q_1^T\right)\cdot A\cdot \left(Q_1\cdots Q_n\right),\nonumber\\
    \end{align}


- Una matriz ortogonal no es más que un cambio de coordenadas, es decir, una rotación. 


- Por ejemplo, en dos dimensiones, N=2:

    $$Q=\left(
    \begin{array}{cc}
    \cos\alpha&-\sin\alpha\nonumber\\
    \sin\alpha&\cos\alpha\nonumber\\
    \end{array}\right),$$


- Al rotar el sistema de coordenadas de nuestra matriz $k$ veces, estamos transformando nuestra matriz en una matriz diagonal.

- La demostración de que en el limite cuando $k\to\infty$ ese es el caso, es complicada, pero se puede entender notando que mientras fuera de la diagonal estamos incluyendo el producto de senos y cosenos, en la diagonal estamos siempre sumando senos y cosenos al cuadrado.


- Por tanto, la idea es continuar el proceso hasta que la matriz $A_k$ se vuelva diagonal.


- Los términos fuera de la diagonal se van haciendo cada vez más pequeños hasta que se hacen cero o tan cercanos a cero que los podemos despreciar.


- Por tanto, dada una precisión podemos diagonalizar la matriz mediante transformaciones de semejanza hasta obtener una matriz diagonal.


- Por tanto, definiendo la matriz ortogonal:

    $$V=\left(Q_1\cdots Q_n\right)=\prod_{i=1}^k Q_i,$$

    obtenemos que:

$$V^T\cdot A\cdot V =D\;\Rightarrow\; A\cdot V = D\cdot V.$$

---

Elegida una precisión $\epsilon$ para los términos de fuera de la diagonal.

1. Crear una matriz V $N \times N$ para contener los autovectores. Inicializar V igual a la matriz identidad.


2. Calcular la factorización QR de $A$: $A = Q\cdot R$.


3. Actualizar $A$ a un nuevo valor $A = R\cdot Q$.


4. Multiplicar $V$ por la derecha por $Q$.


5.  Comprobar los términos no-diagonales de la nueva A. Si son en valor absoluto menores que $\epsilon$, hemos acabado.  

    En caso contrario, volver al paso 2.

---

In [26]:
def module(v):
    """Module of a vector v.

    Args:
        v (np.array): 1-D array.

    Returns:
        np.array: module of argument vector
    """
    return np.sqrt(np.dot(v, v))


def QR(A, eps):
    """QR factorization of matrix A with accuracy eps

    Args:
        A (np.arrayt): matrix to factorize
        eps (float): desired accuracy

    Returns:
        np.array: two matrices corresponding to A's QR factorization
    """
    N = len(A)

    def QR_factorization(A):
        N = len(A)
        U = np.zeros([N, N], float)
        Q = np.zeros([N, N], float)
        R = np.zeros([N, N], float)

        for m in range(N):
            U[:, m] = A[:, m]
            for i in range(m):
                R[i, m] = np.dot(Q[:, i], A[:, m])
                U[:, m] -= R[i, m] * Q[:, i]
            R[m, m] = module(U[:, m])
            Q[:, m] = U[:, m] / R[m, m]
        return Q, R

    V = np.identity(N, float)
    delta = 1.0
    while delta > eps:
        Q, R = QR_factorization(A)
        A = np.dot(R, Q)
        V = np.dot(V, Q)
        Ac = np.copy(A)
        for i in range(N):
            Ac[i, i] = 0.0
        delta = np.max(np.absolute(Ac))
    for i in range(len(Q)):
        for j in range(len(Q)):
            A[i, j] = int(round(A[i, j]))
    return A, V


A = np.array([[1, 4, 8, 4],
              [4, 2, 3, 7],
              [8, 3, 6, 9],
              [4, 7, 9, 2]], float)

D, V = QR(A, 1e-6)
print(D)
print()
print(V)


[[21.  0.  0.  0.]
 [ 0. -8.  0.  0.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0.  1.]]

[[ 0.43151698 -0.38357064 -0.77459666 -0.25819889]
 [ 0.38357063  0.43151698 -0.2581989   0.77459667]
 [ 0.62330228  0.52740965  0.25819889 -0.51639778]
 [ 0.52740965 -0.62330227  0.51639779  0.25819889]]
